Web_page/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session 
from .models import User, Product, Cart, CartItem
from werkzeug.security import generate_password_hash, check_password_hash #SEGURIDAD DE CONTRASEÑA (FUNCION DE UNA VÍA)
from . import db

auth = Blueprint('auth', __name__)

#Ruta para el proceso de login
@auth.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':

        #Obtiene los credenciales que a los que se intentan acceder
        email = request.form.get('email')
        password = request.form.get('password1')

        #Consulta al usuario que coincida con el correo proporcionado      
        user = User.query.filter_by(email=email).first()

        #Verifica que el usuario exista y que la contraseña sea correctay
        if user:

            # Confirma que la contraseña sea correcta
            if check_password_hash(user.password, password):
                flash('Inicio de sesión exitoso!', category='success')
                 
                #Si el usuario es admin, redirige a la página de admin y además asigna las variables del usuario 
                if user.is_admin:
                    session['user_id'] = user.id
                    session['first_name'] = user.first_name
                    return redirect(url_for('views.admin_page'))
                
                #Crea el carrito para el usuario
                cart = Cart.query.filter_by(user_id=user.id).first()

                if cart is None:
                    cart = Cart(user_id=user.id)
                    db.session.add(cart)
                    db.session.commit()

                #Asigna las variables del usuario
                session['user_id'] = user.id
                session['first_name'] = user.first_name

                #Redirige a la página de inicio
                return redirect(url_for('views.home'))

            #Si la contraseña es incorrecta
            else:
                flash('Contraseña incorrecta, intente de nuevo', category= 'error')
        
        #Si el usuario no existe
        else:
            flash('El correo proporcionado no existe, intente de nuevo o cree una cuenta.', category='error')
        
    return render_template("login.html")

# Ruta para el proceso de registro
@auth.route("/sign-up", methods = ['GET', 'POST'])
def signup():

    #Toma los valores ingresados por el usuario
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('first_name')
        last_name = request.form.get("last_name")
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        #Busca en la base de datos si el correo ya está en uso
        user = User.query.filter_by(email=email).first()

        #Si el correo está en uso, se le notifica al usuario
        if user:
            flash('El correo electrónico ya está en uso', category= 'error')

        #Si el correo no está en uso, pero es un correo inválido, se le notifica al usuario
        elif len(email) < 5: 
            flash('El correo debe de contener más de 4 caracteres', category = 'error')
        
        #Si el correo no está en uso, pero las contraseña no coinciden, se le notifica al usuario
        elif password1 != password2:
            flash('Las contraseñas son diferentes', category = 'error')
        elif len(password1) < 6:
            flash('La contraseña debe de tener al menos 6 caracteres', category = 'error')
        
        #Si nada de lo anterior ocurre, se crea el usuario
        else:
            # Se añade al usuario a la base de datos.
            new_user = User(email=email, first_name=first_name, last_name=last_name, password=generate_password_hash(password1)) #Añade el usuario con una contraseña segura
            db.session.add(new_user) #Crea el usuario
            db.session.commit() #Actualiza a base de datos
            flash('Cuenta creada!', category = 'success')

            #Redirige al usuario a la página de inicio
            return redirect(url_for('views.home'))

    #Si el método es GET, se renderiza la página de registro            
    return render_template("signup.html")

@auth.route('/logout')
def logout():
    if 'user_id' not in session:
        return redirect(url_for('views.home'))

    user_id = session['user_id']
    cart = Cart.query.filter_by(user_id=user_id).first()
    if cart:

        #Obtiene los items dentro del carrito
        cart_items = CartItem.query.filter_by(cart_id=cart.id).all()

        #Añade la cantidad al inventario de los items dentro del carrito.
        for item in cart_items:
            product = Product.query.get(item.product_id)
            if product:
                product.quantity += item.quantity
        
        #Elimina la reserva de tiempo del carrito
        cart.time_reserved = None

        CartItem.query.filter_by(cart_id=cart.id).delete()
        db.session.commit()
    session['cart_count'] = 0

    #Elimina al variable de la sesion.
    session.pop('user_id', None)
    return redirect(url_for('views.home'))

Web_page/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="../static/css/styles.css" rel="stylesheet" />

        <title>{%block title%}{%endblock%}</title>
    </head>

    <body style="display: flex; flex-direction: column; min-height: 100vh;"> 
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                {% if 'user_id' in session %}
                    <div class="dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="font-size: 1.2rem;">Hola, {{ session['first_name'] }}!</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                            <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Salir</a></li>
                        </ul>
                    </div>    
                        
                {% else %}
                        <a class="navbar-brand" href="{{url_for('auth.login')}}">Ingresar</a>
                        <a class="navbar-brand" href="{{url_for('auth.signup')}}">Registro</a>

                {% endif %}

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{{url_for('views.home')}}" style="font-size: 1.13em;">Pantalla Principal</a></li>
                            </ul>
                        </li>
                    </ul>
                    <div class="dropdown">
                        <button class="btn btn-outline-dark dropdown-toggle" type="button" id="cartDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi-cart-fill me-1"></i>
                            Carrito
                            <span class="badge bg-dark text-white ms-1 rounded-pill">{{ session['cart_count']|default(0) }}</span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="cartDropdown">
                            {% if session['cart_count']|default(0) > 0 %}
                                <div class="dropdown-item">
                                    <a href="{{ url_for('cart.cart_page') }}">
                                        <button class="btn btn-primary"  style="background-color: black; border-color: black;">Ver Carrito</button>
                                    </a>
                                </div>
                            {% else %}
                                <!-- Display "El carrito está vacío" -->
                                <div class="dropdown-item">
                                    <p>El carrito está vacío</p>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                    <div class="alert alert-danger alert-dismissable fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-bs-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                    </button>
                    </div>

                {% else %}
                    <div class="alert alert-success alert-dismissable fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-bs-dismiss="alert"
                            <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% endwith %}
        <!-- Header-->
        <header class="py-5" style="background: url('https://d21klxpge3tttg.cloudfront.net/wp-content/uploads/2021/06/GRILLED-TOMAHAWKS.jpg') no-repeat 50% 60%; background-size: cover; min-height: 300px;">
        
        </header>



        
        <main style="flex: 1;">
            {% block contents_store %}{% endblock %}
        </main>
  

        <!-- Footer-->
        <footer class="py-5 bg-dark" style="height: 50px";>
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

Web_page/website/templates/cart.html
{% extends "base.html" %}
<title>{% block title %}Carrito{% endblock %}</title>

{%block contents_store %}
<style>
    .table-container {
        display: flex;
        justify-content: center;
        margin-top: 30px; /* Add space above the table */
        margin-bottom: 30px; /* Add space below the table */
    }
    table {
        width: 60%; /* Adjust this to change the table width */
        border-collapse: collapse;
    }
    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: center; /* This centers the text */
    }
    th {
        background-color: #f2f2f2;
    }
</style>

<div class="table-container">
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Peso</th>
                <th>Precio por kilo</th>
                <th>Cantidad</th>
                <th>Precio</th>
            </tr>
        </thead>
        <tbody>
          
            {% for item in cart_items %}
                <tr>
                    <td>
                        {% if item.product.name == 'skirt_steak' %}
                            Skirt Steak (Entraña)

                        {% elif item.product.name == 'ribeye' %}
                            Ribeye

                        {% elif item.product.name == 'picanha' %}
                            Picaña (Punta de Solomo)

                        {% elif item.product.name == 'tomahawk' %}
                            Tomahawk

                        {% elif item.product.name == 'nueva_york'%}
                            Nueva York

                        {% elif item.product.name == 't_bone' %}
                            T Bone
                        
                        {% else %}
                            {{ item.product.name }}
                        {% endif %}
                    </td>
                    <td>{{ item.product.weight }} kg</td>
                    <td>₡{{ "{:,.2f}".format(item.product.base_cost_per_kilogram) }}</td>
                    <td style="display: flex; align-items: center; justify-content: center;">
                        <form method="POST" action="{{ url_for('cart.update_cart', product_id=item.product.id) }}">
                            <select name="quantity" onchange="this.form.submit()">
                                {% for i in range(1, item.quantity + item.product.quantity + 1) %}
                                    <option value="{{ i }}" {% if i == item.quantity %}selected{% endif %}>{{ i }}</option>
                                {% endfor %}
                            </select>
                        </form>
                        <form method="POST" action="{{ url_for('cart.remove_item', product_id=item.product.id) }}" style="margin-left: 10px;">
                            <button type="submit" style="background: none; border: none;">
                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </button>
                        </form>
                    </td>
                    <td>₡{{ "{:,.2f}".format(item.product.base_cost_per_kilogram * item.quantity * item.product.weight) }}</td>
                </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3"></td>
                <td style="text-align: center; border-right: none;">
                    <strong>Precio total:</strong>
                </td>
                <td style="text-align: center; border-left: none;">
                    <strong>₡{{ "{:,.2f}".format(total_price) }}</strong>
                </td>
            </tr>
            <tr>
                <td colspan="3" style="border: none;"></td>
                <td style="border: none;"></td>
                <td style="text-align: center; border: none;">
                    <form method="POST" action="{{ url_for('cart.checkout') }}">
                        <button type="submit" class="btn btn-primary" style="background-color: black; border-color: black;">Comprar</button>
                    </form>
                </td>
            </tr>
        </tfoot>
    </table> 
</div>


{% endblock %}

Web_page/website/templates/delete_product.html
{% extends "admin.html" %}

{% block title %}Delete Stock{% endblock %}

{% block contents_store %}
<style>
    .table-container {
        display: flex;
        justify-content: center;
        margin-top: 30px; /* Add space above the table */
        margin-bottom: 30px; /* Add space below the table */
    }
    table {
        width: 50%; /* Adjust this to change the table width */
        border-collapse: collapse;
        margin: auto; /* This will center the table */
    }
    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: center; /* This centers the text */
        min-height: 70px;
    }
    th {
        background-color: #f2f2f2;
        width: 20%; /* Adjust this to change the column width */
    }
    .submit-button {
        display: flex;
        justify-content: center;
        margin-top: 20px;
    }
    
</style>

{% if products %}
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>Nombre del Producto</th>
                    <th>Peso</th>
                    <th>Costo por kilogramo</th>
                    <th>Costo total</th>
                    <th>Cantidad</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <td>
                            {% if product.name == 'skirt_steak' %}
                                Skirt Steak (Entraña)

                            {% elif product.name == 'ribeye' %}
                                Ribeye

                            {% elif product.name == 'picanha' %}
                                Picaña (Punta de Solomo)

                            {% elif product.name == 'tomahawk' %}
                                Tomahawk

                            {% elif product.name == 'nueva_york'%}
                                Nueva York

                            {% elif product.name == 't_bone' %}
                                T Bone

                            {% else %}
                                {{ product.name }}
                            {% endif %}
                        </td>
                        <td><strong>{{ product.weight }} kg </strong></td>
                        <td>₡{{ "{:,.2f}".format(product.base_cost_per_kilogram) }}</td>
                        <td>₡{{ "{:,.2f}".format(product.total_cost) }}</td>
                        <td> {{ product.quantity }}</td>
                        <td> 
                            <form method="POST" action="{{ url_for('views.delete_product') }}">
                                <input type="hidden" name="product_id" value="{{ product.id }}">
                                <button type="submit" style="background: none; border: none;">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <div style="text-align: center; padding: 20px; font-size: 1.5em;">
        <p>No hay productos</p>
    </div>
{% endif %}

{% endblock %}

Web_page/website/templates/empty_cart.html
{% extends "base.html" %}
<title>{% block title %}Carrito{% endblock %}</title>
{%block contents_store %}
    <h1 style="text-align: center; color: #333; font-size: 2em; margin-top: 2em;">El carrito está vacío!</h1>
{% endblock %}

Web_page/website/templates/login.html
{% extends "base.html" %}

<title>{% block title %}Ingreso- Carnes{% endblock %}</title>


{% block contents_store %}
<div style="width: 30%; margin: 0 auto;" class="mt-3">
    <form method = "POST">
        <h3 align="center">Ingreso</h3>
        <div class="form-group">
            <label for="email">Dirección de correo</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Ingrese el correo" />
        </div>

        <div class="form-group">
            <label for="password1">Contraseña</label>
            <input type="password" class="form-control" id="password1" name="password1" placeholder="Ingrese su contraseña" />
        </div>

        <br />
        <button type="submit" class="btn btn-primary">Ingresar</button>
    </form>
</div>
{%endblock%}

Web_page/website/templates/macros.html
{% macro shop_item(id, image, name, price, url) %}
    <div class="col mb-5" id="{{id}}">
        <div class="card h-100">
                <!-- Product image-->
            <img class="card-img-top" src="{{ url_for('static', filename=image) }}" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">{{ name }}</h5>
                    <!-- Product price-->
                    ₡{{ price }}  x kg
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ url_for(url) }}">Ver producto</a></div>
            </div>
        </div>
    </div>
{% endmacro %}

Web_page/website/templates/nueva_york.html
{% extends "base.html" %}

<title>{% block title %}Nueva York{% endblock %}</title>




{% block contents_store %}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{url_for('static', filename= 'images/nueva_york_main.jpeg')}}" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">SKU: BST-498</div> <!--CAMBIAR!-->
                <h1 class="display-5 fw-bolder">Nueva York</h1> <!--CAMBIAR!-->
                <div class="fs-5 mb-5">
                    {% if products %}
                        <span>₡ {{ "{:,.2f}".format(products[0].base_cost_per_kilogram) }} por kilogramo</span>
                    {% endif %}
                </div>
                <p class="lead"><strong>Forma sugerida de cocinar:</strong> Sellar a alta temperatura en la parrilla y dejar cocinar en calor indirecto hasta llegar a término medio. Dejar reposar luego de terminar la cocción.</p>
                <p class="lead"><strong>Otra forma de cocinar:</strong> Sellar a alta temperatura en un sartén que retenga bien la temperatura y dejar reposar un par de minutos. En otro sarten derretir mantequilla y añadir hierbas deseadas. Introducir la carne en el sartén con la mantequilla y las hierbas y cocinarlo a temperatura media baja, bañandolo constantemente con la mantequilla derretida hasta que alcance el término deseado. Dejar reposar luego de terminar la cocción.</p>                
               
                {% if products %}
                    <form method="post" action="{{ url_for('cart.add_to_cart') }}">
                        <div class="d-flex">
                            <select class="form-control text-center me-3" name="product_id" style="max-width: 17rem">
                                {% for product in products %}
                                    <option value="{{ product.id }}">{{ product.weight }} kg Precio total: ₡ {{ "{:,.2f}".format(product.total_cost) }}</option>
                                {% endfor %}
                            </select>

                            <button type="submit" class="btn btn-outline-dark flex-shrink-0">
                                <i class="bi-cart-fill me-1"></i>
                                Añadir al carrito
                            </button>
                        </div>
                    </form>
                {% else %}
                        <p>Lo sentimos, este producto no está disponible.</p>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{%endblock%}

Web_page/website/templates/picanha.html
{% extends "base.html" %}

<title>{% block title %}Picanha{% endblock %}</title>



{% block contents_store %}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{url_for('static', filename= 'images/picanha_main.jpg')}}" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">SKU: BST-498</div> <!--CAMBIAR!-->
                <h1 class="display-5 fw-bolder">Picaña (Punta de Solomo)</h1> <!--CAMBIAR!-->
                <div class="fs-5 mb-5">
                    {% if products %}
                        <span>₡ {{ "{:,.2f}".format(products[0].base_cost_per_kilogram) }} por kilogramo</span>
                    {% endif %}
                </div>
                <p class="lead"><strong>Forma sugerida de cocinar:</strong> Sellar a alta temperatura en la parrilla y dejar cocinar en calor indirecto hasta llegar a término medio. Dejar reposar luego de terminar la cocción.</p>
                <p class="lead"><strong>Otra forma de cocinar:</strong> Sellar a alta temperatura en un sartén que retenga bien la temperatura y dejar reposar un par de minutos. En otro sarten derretir mantequilla y añadir hierbas deseadas. Introducir la carne en el sartén con la mantequilla y las hierbas y cocinarlo a temperatura media baja, bañandolo constantemente con la mantequilla derretida hasta que alcance el término deseado. Dejar reposar luego de terminar la cocción.</p>                
               
                {% if products %}
                    <form method="post" action="{{ url_for('cart.add_to_cart') }}">
                        <div class="d-flex">
                            <select class="form-control text-center me-3" name="product_id" style="max-width: 17rem">
                                {% for product in products %}
                                    <option value="{{ product.id }}">{{ product.weight }} kg Precio total: ₡ {{ "{:,.2f}".format(product.total_cost) }}</option>
                                {% endfor %}
                            </select>

                            <button type="submit" class="btn btn-outline-dark flex-shrink-0">
                                <i class="bi-cart-fill me-1"></i>
                                Añadir al carrito
                            </button>
                        </div>
                    </form>
                {% else %}
                        <p>Lo sentimos, este producto no está disponible.</p>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{%endblock%}

Web_page/website/templates/ribeye.html
{% extends "base.html" %}

<title>{% block title %}Ribeye{% endblock %}</title>



{% block contents_store %}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{url_for('static', filename= 'images/RIBEYE_MAIN.jpg')}}" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">SKU: BST-498</div> <!--CAMBIAR!-->
                <h1 class="display-5 fw-bolder">Ribeye (Lomo Alto)</h1> <!--CAMBIAR!-->
                <div class="fs-5 mb-5">
                    {% if products %}
                        <span>₡ {{ "{:,.2f}".format(products[0].base_cost_per_kilogram) }} por kilogramo</span>
                    {% endif %}
                </div>
                <p class="lead"><strong>Forma sugerida de cocinar:</strong> Sellar a alta temperatura en la parrilla y dejar cocinar en calor indirecto hasta llegar a término medio. Dejar reposar luego de terminar la cocción.</p>
                <p class="lead"><strong>Otra forma de cocinar:</strong> Sellar a alta temperatura en un sartén que retenga bien la temperatura y dejar reposar un par de minutos. En otro sarten derretir mantequilla y añadir hierbas deseadas. Introducir la carne en el sartén con la mantequilla y las hierbas y cocinarlo a temperatura media baja, bañandolo constantemente con la mantequilla derretida hasta que alcance el término deseado. Dejar reposar luego de terminar la cocción.</p>                
                
                {% if products %}
                    <form method="post" action="{{ url_for('cart.add_to_cart') }}">
                        <div class="d-flex">
                            <select class="form-control text-center me-3" name="product_id" style="max-width: 17rem">
                                {% for product in products %}
                                    <option value="{{ product.id }}">{{ product.weight }} kg Precio total: ₡ {{ "{:,.2f}".format(product.total_cost) }}</option>
                                {% endfor %}
                            </select>

                            <button type="submit" class="btn btn-outline-dark flex-shrink-0">
                                <i class="bi-cart-fill me-1"></i>
                                Añadir al carrito
                            </button>
                        </div>
                    </form>
                {% else %}
                        <p>Lo sentimos, este producto no está disponible.</p>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{%endblock%}

Web_page/website/templates/signup.html
{% extends "base.html" %}

<title>{% block title %}Registro- Carnes{% endblock %}</title>



{% block contents_store %}

<div style="width: 40%; margin: 0 auto;" class="mt-3">
    <form method = "POST">
        <h3 align="center">Registro</h3>
        <div class="form-group">
            <label for="email">Dirección de correo</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Ingrese el correo" />
        </div>

        <div class="form-group">
            <label for="first_name">Primer Nombre</label>
            <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Ingrese su primer nombre" />
        </div>

        <div class="form-group">
            <label for="last_name">Apellido</label>
            <input type="text" class="form-control" id="Last last_name" name="last_name" placeholder="Ingrese su primer apellido" />
        </div>

        <div class="form-group">
            <label for="password1">Contraseña</label>
            <input type="password" class="form-control" id="password1" name="password1" placeholder="Ingrese su contraseña" />
        </div>

        <div class="form-group">
            <label for="password2">Confirme contraseña</label>
            <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirme su contraseña" />
        </div>

        <br />
        <button type="submit" class="btn btn-primary">Registrarse</button>
    </form>
</div>
{%endblock%}